name: Update Meteo Previsions Daily

on:
  schedule:
    - cron: '0 6 * * *'  # Exécuter tous les jours à 06:00 UTC
  workflow_dispatch:  # Permet également de déclencher manuellement

permissions:
  contents: write  # Accorde les permissions de lecture et d'écriture au contenu du dépôt

jobs:
  update-meteo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # Par défaut, mais explicitement mentionné ici

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Spécifiez la version de Python utilisée

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Update Meteo Script
      env:
        API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}  # Utiliser un secret pour la clé API
      run: |
        python update_meteo.py

    - name: Commit and Push Changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add meteo_previsions.csv
        git commit -m "Mise à jour quotidienne des données météo" || echo "Pas de changements à committer"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
